[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects/kaiwei/*"
  to = "/projects/kaiwei/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

