[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects/kaiwei/*"
  to = "/projects/kaiwei/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

